Scrape Artists from Musicbrainz
MusicConnectionMachine/StructuredData pull request #11
Opened 2017-03-09 09:45 UTC by LukasNavickas

2017-03-09 12:53 UTC, sacdallago commented
Put someone as reviewer(s) (not us mentors! We are just reviewing these first PRs thoroughly to teach you _how it's done_, next times we will limit ourselves to close PRs if it's not alright <sorry in advance, happens.>)

2017-03-09 12:54 UTC, sacdallago submitted a review, later dismissed
No scraped data on the repo online! `.gitignore` it and remove it from the PR

2017-03-09 21:21 UTC, kordianbruck commented on scrapeArtists/server.js
> +                'User-Agent': 'ClassicalApp/1.4.0 ( tumiss@gmail.com )'
You should be careful to commit an email address. Github is crawled for such sensitive information

2017-03-13 09:50 UTC, sacdallago commented
Updates on this?

2017-03-13 17:31 UTC, TimHenkelmann commented
Applied tutor suggestions for improvement:
- Removed package.json and outputfile artistsFromRecordings.json
- added .gitignore and artistsFromRecordings_example.json
- applied changes to server.js:
    - removed server
    - removed email

Ready for review!

2017-03-14 17:56 UTC, TimHenkelmann commented
Hi @sacdallago. I have a question for this one. I removed the scraped output (artistsFromRecordings.js) from the PR. However, the server.js script needs to read data from "IDArtistsRecordingsFinal2.json" (an input file which contains scraped data from another script).
How should we proceed with that:
- Remove the input file as well
- Rename it and only show a few entries (then one would also need to change the server.js file)
- Keep the name of the input file and only have it contain a few entries
-  Something completely different

Thanks in advance

2017-03-14 21:56 UTC, kordianbruck requested changes

2017-03-14 21:56 UTC, kordianbruck commented on scrapeArtists/artistsFromRecordings_example.json
> +{"table":[{"artistId":"e8c91353-e251-456b-80ad-d10c2cd00be3","aboutartist":{"gender":null,"isnis":[],"id":"e8c91353-e251-456b-80ad-d10c2cd00be3","life-span":{"ended":false,"end":null,"begin":null},"n
Please don't commit these json files. It only blows up your Git History and makes it slow.

2017-03-14 21:57 UTC, kordianbruck commented on scrapeArtists/artistsFromRecordings_example.json
> +{"table":[{"artistId":"e8c91353-e251-456b-80ad-d10c2cd00be3","aboutartist":{"gender":null,"isnis":[],"id":"e8c91353-e251-456b-80ad-d10c2cd00be3","life-span":{"ended":false,"end":null,"begin":null},"n
Or is it intended?

2017-03-14 21:59 UTC, kordianbruck commented
@TimHenkelmann - you should only write files to disk as a cache. Ideally we only start one server / script that will handle all scraping and loading while keeping everything in ram. (We have kinda unlimited Ram)

2017-03-15 09:12 UTC, sacdallago commented
Mh, if I understood correctly: this script has a dependency on another script to get data, right?

Natural thing to do would chain these two scripts together, something like:

```
IF NOT dataFromScriptOne exists:
   require scriptOne
   run scriptOne.getData
   run script
ELSE
   run script
```

2017-03-15 11:13 UTC, metavaults reviewed
- did all changes according to reviewers

2017-03-15 11:36 UTC, TimHenkelmann commented on scrapeArtists/artistsFromRecordings_example.json
> +{"table":[{"artistId":"e8c91353-e251-456b-80ad-d10c2cd00be3","aboutartist":{"gender":null,"isnis":[],"id":"e8c91353-e251-456b-80ad-d10c2cd00be3","life-span":{"ended":false,"end":null,"begin":null},"n
@kordianbruck Yes, this is only an extract of the complete json output file and displays how the data is going to look like

2017-03-16 12:02 UTC, kordianbruck commented
@MusicConnectionMachine/group-1 please also review this! Its been waiting for **7 days** - ahhhh :angry:

2017-03-16 13:39 UTC, TimHenkelmann commented
Hi @kordianbruck , there are still "requested changes" from your side (probably from the .json file that we had in there at first but now deleted). Could you accept them or comment on that?
Thx!

2017-03-16 13:42 UTC, kordianbruck requested changes
Last thing.

2017-03-16 13:42 UTC, kordianbruck commented on scrapeArtists/server.js
> +    setInterval(function(){
Why are you using a setInterval here?

2017-03-16 13:48 UTC, LukasNavickas commented on scrapeArtists/server.js
> +    setInterval(function(){
In order to get 100% of results, we cannot query MusicBrainz faster than every second. 
Reference: https://musicbrainz.org/doc/XML_Web_Service/Rate_Limiting

2017-03-16 13:53 UTC, kordianbruck commented on scrapeArtists/server.js
> +    setInterval(function(){
Ugly solution. Might want to reconsider this in the future.

2017-03-16 13:53 UTC, kordianbruck approved these changes

2017-03-16 13:55 UTC, TimHenkelmann commented on scrapeArtists/server.js
> +    setInterval(function(){
Alright, we will try to find other approaches for this in the future!

2017-03-16 13:55 UTC, merged

2017-03-16 14:09 UTC, kordianbruck commented on scrapeArtists/server.js
> +    setInterval(function(){
Yea, don't worry about it now.