script to scrape composers from classical era
MusicConnectionMachine/StructuredData pull request #12
Opened 2017-03-09 12:00 UTC by ShilpaGhanashyamGore

2017-03-09 12:06 UTC, angelinrashmi2000 commented
Shilpa look into the formatting

2017-03-09 12:42 UTC, sacdallago commented
@angelinrashmi2000 please be more specific and use [the review button in the "files changed" section](https://help.github.com/articles/about-pull-request-reviews/) to propose changes if they are necessary, or approve the merge :)

2017-03-09 12:47 UTC, sacdallago requested changes

2017-03-09 12:47 UTC, sacdallago commented on scrape_dbPedia.js
> +var express = require('express');
`var` vs `const` vs `let`. Are they variables, constants or scope-specific? Be consistent with the use of these!

2017-03-09 12:47 UTC, sacdallago commented on scrape_dbPedia.js
> +  fs.readFile('myjsonfile2.json', 'utf-8', function(err, array) {
[Here](https://github.com/MusicConnectionMachine/StructuredData/pull/12/files#diff-815b15a3748d5c262f4563790a730a0dR15) you use ES2015/ES6 syntax to write a function callback (`(param) ==> { //doSomething }`), while in this line you use ES5 (`function(param){ //doSomething }`). Stick to one standard, it's more readable :)

2017-03-09 12:47 UTC, sacdallago commented on scrape_dbPedia.js
> +								if(html){
This seems too much indented?

2017-03-09 13:20 UTC, sacdallago commented
@ShilpaGhanashyamGore you can't commit on develop, nor you should. See "Feature Branch Workflow" [here](https://www.atlassian.com/git/tutorials/comparing-workflows)

2017-03-09 13:58 UTC, ShilpaGhanashyamGore commented
@sacdallago :Thank you for the review comments ! I shall incorporate them

2017-03-14 18:10 UTC, TimHenkelmann commented
This was not a valid branch so we decided to close this PR.

2017-03-14 18:10 UTC, closed without merging